without libraries

In [ ]:
Yact = [10, 20, 30, 40, 50]
Ypred = [10.2, 20.5, 30.3, 40.8, 50.6]

n = len(Yact)
squared_error = 0
absolute_error = 0

for actual, predicted in zip(Yact, Ypred):
    error = actual - predicted
    squared_error += error ** 2
    absolute_error += abs(error)

mse = squared_error / n
mae = absolute_error / n
rmse = mse ** 0.5

print(f"Mean Squared Error (MSE): {mse}")
print(f"Mean Absolute Error (MAE): {mae}")
print(f"Root Mean Squared Error (RMSE): {rmse}")

Mean Squared Error (MSE): 0.27599999999999947
Mean Absolute Error (MAE): 0.4799999999999997
Root Mean Squared Error (RMSE): 0.5253570214625474


with libraries

In [ ]:
import numpy as np
Yact = np.array([10, 20, 30, 40, 50])
Ypred = np.array([10.2, 20.5, 30.3, 40.8, 50.6])

mse = np.mean((Yact - Ypred) ** 2)
mae = np.mean(np.abs(Yact - Ypred))
rmse = np.sqrt(mse)

print(f"Mean Squared Error (MSE): {mse}")
print(f"Mean Absolute Error (MAE): {mae}")
print(f"Root Mean Squared Error (RMSE): {rmse}")

Mean Squared Error (MSE): 0.27599999999999947
Mean Absolute Error (MAE): 0.4799999999999997
Root Mean Squared Error (RMSE): 0.5253570214625474


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

Yact = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2]
Ypredict = [0, 0, 1, 1, 2, 2, 0, 1, 1, 1, 2, 0, 2, 1, 1, 2]

conf_matrix = confusion_matrix(Yact, Ypredict)

accuracy = accuracy_score(Yact, Ypredict)

print("Confusion Matrix:")
print(conf_matrix)
print("\nAccuracy:")
print(accuracy)

Confusion Matrix:
[[2 2 1]
 [1 3 2]
 [1 2 2]]

Accuracy:
0.4375


#2

In [ ]:
ya1=[0,0,0,0,0,1,1,1,1,1,1,2,2,2,2,2]
yp1=[0,0,1,1,2,2,0,1,1,1,2,0,2,1,1,2]

In [ ]:
min_label = min(min(ya1), min(yp1))
max_label = max(max(ya1), max(yp1))


num_classes = max_label - min_label + 1

cm = [[0 for _ in range(num_classes)] for _ in range(num_classes)]

for i in range(len(ya1)):
    cm[ya1[i]-min_label][yp1[i]-min_label] += 1

for row in cm:
    print(row)


[2, 2, 1]
[1, 3, 2]
[1, 2, 2]


In [ ]:
import numpy as np
accuracy = np.sum(np.diagonal(cm)) / np.sum(cm)

precision = {}
recall = {}
f1_score = {}

for i in range(num_classes):
    true_positive = cm[i][i]
    false_positive = np.sum(cm[j][i] for j in range(num_classes)) - true_positive
    false_negative = np.sum(cm[i][j] for j in range(num_classes)) - true_positive
    true_negative = np.sum(np.sum(cm[row][col] for col in range(num_classes)) for row in range(num_classes)) - (true_positive + false_positive + false_negative)

    # Precision: TP / (TP + FP)
    precision[i] = true_positive / (true_positive + false_positive) if (true_positive + false_positive) > 0 else 0

    # Recall: TP / (TP + FN)
    recall[i] = true_positive / (true_positive + false_negative) if (true_positive + false_negative) > 0 else 0

    # F1 Score: 2 * (Precision * Recall) / (Precision + Recall)
    if precision[i] + recall[i] > 0:
        f1_score[i] = 2 * (precision[i] * recall[i]) / (precision[i] + recall[i])
    else:
        f1_score[i] = 0


overall_precision = np.sum([precision[i] for i in range(num_classes)])/num_classes
overall_recall = np.sum([recall[i] for i in range(num_classes)])/num_classes
overall_f1_score = np.sum([f1_score[i] for i in range(num_classes)])/num_classes

for i in range(num_classes):
    print(f"\nClass {i + min_label}:")
    print(f"  Precision: {precision[i]:.2f}")
    print(f"  Recall: {recall[i]:.2f}")
    print(f"  F1-Score: {f1_score[i]:.2f}")


print("\nMetrics:")
print(f"Overall Accuracy: {accuracy:.2f}")
print(f"Overall Precision: {overall_precision:.2f}")
print(f"Overall Recall: {overall_recall:.2f}")
print(f"Overall F1-Score: {overall_f1_score:.2f}")

print()
print()


Class 0:
  Precision: 0.50
  Recall: 0.40
  F1-Score: 0.44

Class 1:
  Precision: 0.43
  Recall: 0.50
  F1-Score: 0.46

Class 2:
  Precision: 0.40
  Recall: 0.40
  F1-Score: 0.40

Metrics:
Overall Accuracy: 0.44
Overall Precision: 0.44
Overall Recall: 0.43
Overall F1-Score: 0.44




<ipython-input-6-ba1a55991cd3>:10: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  false_positive = np.sum(cm[j][i] for j in range(num_classes)) - true_positive
<ipython-input-6-ba1a55991cd3>:11: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  false_negative = np.sum(cm[i][j] for j in range(num_classes)) - true_positive
<ipython-input-6-ba1a55991cd3>:12: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  true_negative = np.sum(np.sum(cm[row][col] for col in range(num_classes)) for row in range(num_classes)) - (true_positive + false_positive + false_negative)


with libraries

In [ ]:
from sklearn.metrics import accuracy_score,precision_score,f1_score,recall_score,classification_report,confusion_matrix
print(confusion_matrix(ya1,yp1))

[[2 2 1]
 [1 3 2]
 [1 2 2]]


In [ ]:
print(classification_report(ya1,yp1))

              precision    recall  f1-score   support

           0       0.50      0.40      0.44         5
           1       0.43      0.50      0.46         6
           2       0.40      0.40      0.40         5

    accuracy                           0.44        16
   macro avg       0.44      0.43      0.44        16
weighted avg       0.44      0.44      0.44        16



In [ ]:
print("\nMetrics:")
print(f"Overall Accuracy: {accuracy_score(ya1,yp1):.2f}")
print(f"Overall Precision: {precision_score(ya1,yp1, average='weighted'):.2f}")
print(f"Overall Recall: {recall_score(ya1,yp1, average='weighted'):.2f}")
print(f"Overall F1-Score: {f1_score(ya1,yp1, average='weighted'):.2f}")


Metrics:
Overall Accuracy: 0.44
Overall Precision: 0.44
Overall Recall: 0.44
Overall F1-Score: 0.44
